{{- if and .Values.ingress.enabled .Values.ingress.client.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.client.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.client.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.client.path }}
            pathType: {{ .Values.ingress.client.pathType }}
            backend:
              service:
                name: {{ .Values.ingress.client.service.name }}
                port:
                  number: {{ .Values.ingress.client.service.port }}

{{- end }}