apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.job.sql.configMapName }}
data:
  {{ .Values.postgres.job.sql.fileName }}: |
{{ .Files.Get (printf "sql/%s" .Values.postgres.job.sql.fileName) | indent 4 }}
