apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job
spec:
  backoffLimit: {{ .Values.postgres.job.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.postgres.job.activeDeadlineSeconds }}

  template:
    metadata:
      labels:
        app: postgres-init-job

    spec:
      restartPolicy: {{ .Values.postgres.job.restartPolicy }}

      containers:
        - name: postgres-init

          image: "{{ .Values.postgres.job.image.repository }}:{{ .Values.postgres.job.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.job.image.pullPolicy }}

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."

              until pg_isready \
                -h postgres-service \
                -U "$POSTGRES_USER" \
                -d "$POSTGRES_DB"
              do
                echo "PostgreSQL is not ready yet..."
                sleep 5
              done

              echo "PostgreSQL is ready."

              echo "Executing SQL script..."

              psql \
                -h postgres-service \
                -U "$POSTGRES_USER" \
                -d "$POSTGRES_DB" \
                -f /sql/fyp_db.sql

              echo "Database initialization completed."

          volumeMounts:
            - name: postgres-init-script
              mountPath: /sql
              readOnly: true

      volumes:
        - name: postgres-init-script
          configMap:
            name: {{ .Values.postgres.job.sql.configMapName }}
