apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  PORT: {{ .Values.server.config.PORT | quote}}
  JWT_SECRET: {{ .Values.server.config.JWT_SECRET | quote}}
  JWT_EXPIRES_IN: {{ .Values.server.config.JWT_EXPIRES_IN | quote}}
  NODE_ENV: {{ .Values.server.config.NODE_ENV | quote}}
  EMAIL_SERVICES: {{ .Values.server.config.EMAIL_SERVICES | quote}}
  EMAIL_USER: {{ .Values.server.config.EMAIL_USER | quote}}
  EMAIL_PASSWORD: {{ .Values.server.config.EMAIL_PASSWORD | quote}}
  EMAIL_FROM_NAME: {{ .Values.server.config.EMAIL_FROM_NAME | quote}}
  VAPID_PUBLIC_KEY: {{ .Values.server.config.VAPID_PUBLIC_KEY | quote}}
  VAPID_PRIVATE_KEY: {{ .Values.server.config.VAPID_PRIVATE_KEY | quote}}
  VAPID_EMAIL: {{ .Values.server.config.VAPID_EMAIL | quote}}
  DB_HOST: {{ .Values.server.config.DB_HOST | quote}}
  DB_USER: {{ .Values.server.config.DB_USER | quote}}
  DB_PASSWORD: {{ .Values.server.config.DB_PASSWORD | quote}}
  DB_NAME: {{ .Values.server.config.DB_NAME | quote}}
  DB_PORT: {{ .Values.server.config.DB_PORT | quote}}
