apiVersion: v1
kind: Secret
metadata:
  name: ghcr-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: ghcr-helm-repo
  type: helm
  url: ghcr.io/qais001-pr
  enableOCI: "true"
  username: qais001-pr
  password: XXXXXXXXXXYYYYYYYYYYYZZZZZZZZZZ
