services:
  postgres:
    image: postgres:17-alpine
    container_name: fyp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fyp_db
    ports:
      - "5432:5432"
    volumes:
      - fyp_postgres_data:/var/lib/postgresql/data
      - ./database/fyp_db.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - fyp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5



  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fyp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fyp_network
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fyp_backend
    env_file: ./backend/.env
    ports:
      - "7860:7860"
    depends_on:
      postgres: 
        condition: service_healthy
    networks:
      - fyp_network
    restart: unless-stopped
  web-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fyp_web_app
    env_file:
    - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fyp_network
    restart: unless-stopped

volumes:
  fyp_postgres_data:
  pgadmin_data:

networks:
  fyp_network:
    driver: bridge