{{- if .Values.networkPolicy.serverIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.serverIngress.name }}

spec:
  podSelector:
    matchLabels:
      app: {{ .Values.networkPolicy.serverIngress.targetPod }}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.serverIngress.namespace }}
          podSelector:
            matchLabels:
              {{ .Values.networkPolicy.serverIngress.labelKey }}: {{ .Values.networkPolicy.serverIngress.controller }}
{{- end }}