{{- if .Values.networkPolicy.serverEgress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.serverEgress.name }}

spec:
  podSelector:
    matchLabels:
      app: {{ .Values.networkPolicy.serverEgress.sourcePod }}

  policyTypes:
    - Egress

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.networkPolicy.serverEgress.destinationPod }}
{{- end }}