apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: {{ .Values.pgadmin.service.type }}
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: {{ .Values.pgadmin.service.targetPort }}
