apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: {{ .Values.postgres.persistentStorage.nodeSelector.key }}
              operator:  {{ .Values.postgres.persistentStorage.nodeSelector.operator }}
              values:
               {{- range .Values.postgres.persistentStorage.nodeSelector.values }} 
                 - {{ . }}
               {{- end }}

  capacity:
    storage: {{ .Values.postgres.persistentStorage.capacity.storage }}
  volumeMode: {{ .Values.postgres.persistentStorage.capacity.volumeMode }}
  accessModes:
    {{- range .Values.postgres.persistentStorage.accessModes }}
      - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.postgres.persistentStorage.pvReclaimPolicy }}
  storageClassName: {{ .Values.postgres.persistentStorage.storageClassName }}
  hostPath:
    path: {{ .Values.postgres.persistentStorage.hostpath }}