apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.postgres.persistentStorage.capacity.storage }}
  volumeMode: {{ .Values.postgres.persistentStorage.capacity.volumeMode }}
  accessModes:
    {{- range .Values.postgres.persistentStorage.accessModes }}
      - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.postgres.persistentStorage.storageClassName }}
