export const QUERY_KEYS = {
  AUTH: {
    ME: "me",
    LOGIN: "login",
    REGISTER: "register",
    VERIFY_OTP: "verify_otp",
    RESEND_OTP: "resend_otp",
    FORGET_PASSWORD: "forgot_password",
    RESET_PASSWORD: "reset_password",
  },
  SCHOOL: {
    ALL_SCHOOLS: "all_schools",
  },
  PARENT: {
    ADD_CHILD: "add_child",
    CHILDREN: "children",
    CHILD_DETAIL: "child_detail",
    UPDATE_CHILD_DETAIL: "update_child_detail",
    DELETE_CHILD: "delete_child",
    GIVE_FEEDBACK: "give_feedback",
    VAN_FEEDBACK: "van_feedback",
    FEEDBACK_HISTORY: "feedback_history",
    GIVE_COMPLAINT: "give_complaint",
    COMPLAINT_HISTORY: "complaint_history",
    PAYMENT: "payment",
    PAY_NOW: "pay_now",
    PAYMENT_HISTORY: "payment_history",
    ALL_ACTIVE_VANS: "all_active_vans",
    VAN_DETAIL: "van_detail",
    BOOK_VAN: "book_van",
    BOOKINGS: "bookings",
    CANCEL_BOOKING: "cancel_booking",
    RE_BOOKING: "re_booking",
    BOOKING_DETAIL: "booking_detail",
    ALL_BOOKED_DRIVERS: "all_booked_drivers",
    LEAVE_HISTORY: "leave_history",
    LEAVE_REQUEST: "leave_request",
    CHILDREN_FOR_LEAVE: "children_for_leave",
  },
  DRIVER: {
    ROUTE_DETAIL: "driver_route_detail",
    CREATE_ROUTE: "driver_create_route",
    MY_ROUTES: "driver_my_routes",
    UPDATE_ROUTE: "driver_update_route",
    DELETE_ROUTE: "driver_delete_route",
    ASSIGNED_STUDENTS: "driver_assigned_students",
    ALL_STUDENTS: "driver_all_students",
    STUDENT_DETAIL: "driver_student_detail",
    EARNING: "driver_earning",
    EARNING_PER_STUDENTS: "driver_earning_per_students",
    LATEST_EARNINGS: "driver_latest_earnings",
    STUDENT_PAYMENT_HISTORY: "driver_student_payment_history",
    LEAVE_DRIVER: "driver_leave",
    RESTORE_DRIVER: "driver_restore",
    NEW_DRIVERS: "driver_new_drivers",
    ASSIGNED_DRIVERS: "driver_assigned_drivers",
    STUDENT_FEEDBACK: "driver_student_feedback",
    STUDENT_FEEDBACK_HISTORY: "driver_student_feedback_history",
    STUDENT_COMPLAINT: "driver_student_complaint",
    STUDENT_COMPLAINT_HISTORY: "driver_student_complaint_history",
    VANS: "driver_vans",
    ADD_VAN: "driver_add_van",
    UPDATE_VAN: "driver_update_van",
    DELETE_VAN: "driver_delete_van",
    REPORTS: "driver_reports",
    DELAY_REPORTS: "driver_delay_reports",
  },
};
