apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: vansystem
data:
  PORT: "7860"
  JWT_SECRET: bbiuuibtyrt352w43w34w545sw4s5e34srcgftjycc
  JWT_EXPIRES_IN: 1d
  NODE_ENV: development
  EMAIL_SERVICES: gmail
  EMAIL_USER: zamanyaseen2024@gmail.com
  EMAIL_PASSWORD: xein fjwl isdn wwcj
  EMAIL_FROM_NAME: Van Pooling Management System
  FRONTEND_URL: http://localhost:3000
  CLOUDINARY_URL: cloudinary://251979327913559:FZo3uSU9ITLDf4dlVBxSkI972rs@dxgj1uzdv
  CLOUDINARY_CLOUD_NAME: dxgj1uzdv
  CLOUDINARY_API_KEY: "251979327913559"
  CLOUDINARY_API_SECRET: FZo3uSU9ITLDf4dlVBxSkI972rs
  VAPID_PUBLIC_KEY: BEIYJ2sjG7swDP7AJvDSpZK1hSaakzJs-PWtfyZnXsK6PDmXbZgyfHygKnjGR25JqOswaRdYXs4IWsQi9UvZgRg
  VAPID_PRIVATE_KEY: TWwulAERND0eRL3zz-wpX_3P-hx7CW_-3pWgeXolWt4
  VAPID_EMAIL: zamanyaseen2024@gmail.com
  DB_HOST: postgres-service
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: fyp_db
  DB_PORT: "5432"
