apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: vansystem
data:
  PORT: "7860"
  JWT_SECRET: XXXXXXXXXX
  JWT_EXPIRES_IN: 1d
  NODE_ENV: development
  EMAIL_SERVICES: gmail
  EMAIL_USER: XXXXXXXXXXXXX@gmail.com
  EMAIL_PASSWORD: XXXXXXXXXXXX
  EMAIL_FROM_NAME: XXXXXXX
  FRONTEND_URL: XXXXXXXX
  CLOUDINARY_URL: cloudinary://XXXXXXXXX:XXXXXXXXXXX@XXXXXXXXX
  CLOUDINARY_CLOUD_NAME: XXXXXXXXXX
  CLOUDINARY_API_KEY: "XXXXXXXXXX"
  CLOUDINARY_API_SECRET: XXXXXXXXXX
  VAPID_PUBLIC_KEY: XXXXXXXXXX
  VAPID_PRIVATE_KEY: XXXXXXXXXX
  VAPID_EMAIL: XXXXXXXXXXXXX@gmail.com
  DB_HOST: postgres-service
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: fyp_db
  DB_PORT: "5432"
