apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: vansystem
spec:
  replicas: 1
  selector:

    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: pgadmin-secret
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
          - mountPath: /data/pgadmin
            name: pgadmin-storage
        ports:
        - containerPort: 80
        
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc
