apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: vansystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: qais001/vansystem-webapp:v4.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
