name: Backend-Continuous-Integration

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Images
        run: docker build -t qais001-pr/school-transport-system:${{ github.sha }} ./backend
      - name: Check Docker Images
        run: docker images
      - name: Push Docker Images
        run: docker push qais001/school-transport-system:${{ github.sha }}
