name: Backend-Continuous-Integration

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build Docker Images
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/school-transport-system:${{ github.ref_name }} ./backend
      # - name: Check Docker Images
      #   run: docker images
      # - name: Push Docker Images
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/school-transport-system:${{ github.ref_name }}
      - name: Setup Helm
        uses: azure/setup-helm@v4
      - name: Login Helm
        run: echo ${{ secrets.HELM_TOKEN }} | helm registry login ghcr.io -u qais001-pr --password-stdin
      - name: Pull Helm Package From GHCR
        run: helm pull oci://ghcr.io/qais001-pr/school-transport-management-system --version 0.1.1
      - name: List all dir
        run: ls -al
      - name: Unzip Helm Package
        run: tar -xzf school-transport-management-system-0.1.1.tgz
      - name: List all dir
        run: ls -al
      - name: Check Helm Package
        run: cd school-transport-management-system && ls -al
      - name: Lint Helm Package
        run: helm lint school-transport-management-system-0.1.1
      - name: Render Helm Templates
        run: helm template test-release ./school-transport-management-system
